%function createfigure1(X1, YMatrix1)
%CREATEFIGURE1(X1,YMATRIX1)
%  X1:  vector of x data
%  YMATRIX1:  matrix of y data

%  Auto-generated by MATLAB on 12-Mar-2010 13:40:11

global Tagg Struct modelAtm MassforPlotAlpha
% Create figure
figure1 = figure('InvertHardcopy','off','Color',[1 1 1]);

MassX01_wall = MassforPlotAlpha(3,:)./(MassforPlotAlpha(1,:)+MassforPlotAlpha(3,:)+MassforPlotAlpha(4,:));
MassX01_susp = MassforPlotAlpha(7,:)./(MassforPlotAlpha(5,:)+MassforPlotAlpha(7,:)+MassforPlotAlpha(8,:));

% Create axes
axes1 = axes('Parent',figure1,'LineWidth',2,'FontSize',16);
% Uncomment the following line to preserve the X-limits of the axes
% xlim([0 3]);
% Uncomment the following line to preserve the Y-limits of the axes
% ylim([0.5 1]);
% Uncomment the following line to preserve the Z-limits of the axes
% zlim([-1 1]);
box('on');
hold('all');

% Create multiple lines using matrix input to plot
%plot1 = plot(X1,YMatrix1,'Parent',axes1,'LineWidth',2);

if modelAtm.Pop>6
    plot1 = plot(Tagg/3600,Struct.P1.XCpT_1,Tagg/3600,Struct.P2.XCpT_1,Tagg/3600,Struct.P3.XCpT_1,Tagg/3600,Struct.P4.XCpT_1, Tagg/3600, Struct.P5.XCpT_1, ...
        Tagg/3600, Struct.P6.XCpT_1, Tagg/3600, Struct.P7.XCpT_1, 'Parent',axes1,'LineWidth',2);
elseif modelAtm.Pop>3
    plot1 = plot(Tagg/3600,Struct.P1.XCpT_1,Tagg/3600,Struct.P2.XCpT_1,Tagg/3600,Struct.P3.XCpT_1,Tagg/3600,Struct.P4.XCpT_1,'Parent',axes1,'LineWidth',2);
else
    plot1 = plot(Tagg/3600,MassX01_wall',Tagg/3600,MassX01_susp','Parent',axes1,'LineWidth',2);
    %plot1 = plot(Tagg/3600,MassX01_susp','Parent',axes1,'LineWidth',2); 
end



set(plot1(1),'DisplayName','Suspension');
set(plot1(2),'DisplayName','Wall');
if modelAtm.Pop>3
set(plot1(3),'DisplayName','Pop 3');
set(plot1(4),'DisplayName','Pop 4');
end
if modelAtm.Pop>6
   set(plot1(5), 'DisplayName','Pop 5'); 
   set(plot1(6), 'DisplayName','Pop 6'); 
   set(plot1(7), 'DisplayName','Pop 7'); 
end

% Create xlabel
xlabel({'Time (hr)'},'FontSize',16);

% Create ylabel
ylabel({'X(C*=1)'},'FontSize',16);

%axis([1 5 0 1]);

% Create legend
legend(axes1,'show');

%set(legend1,'Position',[0.5206 0.1837 0.3589 0.1601])

% Set the size of the figure on the screen and for printing
% Rediculously complicated but such is life
paperSize = [5 4];
set(gcf,'Units','inches');
pos = get(gcf,'Position');
set(gcf,'Position',[[pos(1) pos(2)]  paperSize]);
set(gcf,'PaperPosition',[[0 0] paperSize]);
set(gcf, 'PaperUnits', 'inches');
set(gcf, 'PaperSize', paperSize);
set(gcf,'Color','none');
legend1 = legend(axes1,'show');
if modelAtm.BGBin==1
set(legend1,'Position',[0.5139 0.1753 0.3589 0.1601]);
else
set(legend1,'Position',[0.5206 0.7364 0.3589 0.1601]);
end
axis([0 5 0 1]);
% Make sure there is a place for figures and save as a pdf
if ~exist('./figs','dir'); mkdir('./figs'); end;
saveas(gcf,['./figs/MolFrac.pdf'],'pdf'); 
