function createfigure(X1, ymatrix1)
%CREATEFIGURE(X1,YMATRIX1)
%  X1:  area x
%  YMATRIX1:  area matrix data

%  Auto-generated by MATLAB on 21-Jan-2010 22:46:10

% Create figure
figure1 = figure('XVisual',...
    '0x24 (TrueColor, depth 24, RGB mask 0xff0000 0xff00 0x00ff)',...
    'InvertHardcopy','off',...
    'Color',[1 1 1]);

% Create axes
axes1 = axes('Parent',figure1,'LineWidth',3,'FontSize',24);
% Uncomment the following line to preserve the X-limits of the axes
% xlim([0 10]);
% Uncomment the following line to preserve the Y-limits of the axes
% ylim([0 2e-08]);
% Uncomment the following line to preserve the Z-limits of the axes
% zlim([-1 1]);
box('on');
hold('all');

% Create multiple lines using matrix input to area
area1 = area(X1,ymatrix1,'Parent',axes1);
set(area1(1),'FaceColor',[1 0 0],'DisplayName','Sulfate');
set(area1(2),'FaceColor',[0 1 0],'DisplayName','Organics');

% Create xlabel
xlabel('Time (hr)','FontSize',24);

% Create ylabel
ylabel('Coating mass (\mug)','FontSize',24);

% Create legend
legend(axes1,'show');

